server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      #集群配置
      #defaultZone: http://slave1.eureka.com:8761/eureka/,http://slave2.eureka.com:8762/eureka/
      #单机
      defaultZone: http://eureka.com:8761/eureka/

first-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.lucien.sise.config.ribbon.MyRule
    NFLoadBalancerPingClassName: com.lucien.sise.config.ribbon.MyPing
    listOfServers: http://localhost:8001,http://localhost:8005
