#此处可以在启动时给jvm指定参数 -Dserver.port=8081 改变端口号或者直接改这里就行，不必像老师那样复杂
server:
  port: 8001

spring:
  application:
    name: first-provider

eureka:
  #客户端注册进eureka服务列表内
  client:
    service-url:
      #集群配置
      #defaultZone: http://slave1.eureka.com:8761/eureka/,http://slave2.eureka.com:8762/eureka/
      #单机
      defaultZone: http://eureka.com:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

info:
  app.name: sise
  company.name: www.lucien.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
