server:
  port: 8081

spring:
  application:
    name: first-consumer
  rabbitmq:
    host: 192.168.56.254
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        myInput:
          group: groupA

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka.com:7000/eureka/