server:
  port: 80

spring:
  application:
    name: zuul-gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka.com:7000/eureka/

zuul:
  routes:
    person.serviceId: provider
    person.path: /person/**